name: Generate Holiday Calendar

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  generate-calendar:
    defaults:
      run:
        working-directory: helpers/holiday_csv

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6

    - name: Generate holiday calendar
      run: |
        mkdir -p public
        uv run holidays > public/holidays.csv

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: helpers/holiday_csv/public/


  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-calendar
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
